### Add a New Post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "My First Post",
    "content": "This is the content of my first post",
    "sender": "user123"
}

### Get All Posts
GET http://localhost:3000/posts

### Get a Post by ID
GET http://localhost:3000/posts/6737533d3a7731255c1879ad

### Get Posts by Sender
GET http://localhost:3000/posts/sender/user123

### Update a Post
PUT http://localhost:3000/posts/6737533d3a7731255c1879ad
Content-Type: application/json

{
    "title": "Updated Post",
    "content": "Updated content"
}


